spring.application.name=Career-Compass

spring.datasource.url=jdbc:mysql://localhost:3306/Final_db
spring.datasource.username=root
spring.datasource.password=113114

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Run SQL scripts on startup
spring.sql.init.mode=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dzeepost@gmail.com
spring.mail.password=gfwu jfom khse lrnj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# AI Quiz Python API URL
ai.quiz.url=http://localhost:8000/start

# Added for Spring Boot web server configuration
server.port=8080
